### ISSUE TITLE
Cannot set drawable at runtime

### ISSUE THREAD

**Issue by tabassumLatif** [Pulimet/Indicators-Library#1]
Cannot  set drawable icon and background color for selected and unselected indicator at run time (in java file)

**Comment by Pulimet** [comment]
Thanks. I will check ASAP.

**Comment by Pulimet** [comment]
New drawable setters for selected/unselected indicators added.

_Update dependency to use them:
compile 'net.alexandroid.utils:indicators:1.4'_

![new_feature](https://user-images.githubusercontent.com/6112126/30967370-c131573c-a464-11e7-9a1d-554a1509f742.gif)
