### ISSUE TITLE
is possible change size?

### ISSUE THREAD

**Issue by NunciosChums** [Pulimet/Indicators-Library#2]
like this?
```
app:selectedSize="12dp"
app:unSelectedSize="12dp"
```

**Comment by Pulimet** [comment]
I added it for you in version 1.5: 
```
            app:indicatorSelectedSize="30dp"
            app:indicatorSize="20dp"
```

**Comment by NunciosChums** [comment]
thank you!
but I found another issue that's related.

```xml
<net.alexandroid.utils.indicators.IndicatorsView
  android:id="@+id/indicator"
  android:layout_width="wrap_content"
  android:layout_height="wrap_content"
  android:gravity="center_vertical"
  android:orientation="horizontal"
  app:indicatorSelectedSize="12dp"
  app:indicatorSize="8dp"
  app:layout_constraintBottom_toBottomOf="@+id/btn_next"
  app:layout_constraintEnd_toEndOf="parent"
  app:layout_constraintStart_toStartOf="parent"
  app:layout_constraintTop_toTopOf="@+id/btn_next"
  app:paddingBetweenIndicators="6dp"
  app:selectedDrawable="@drawable/bg_indicator_selected"
  app:unSelectedDrawable="@drawable/bg_normal"/>
```
<img width="132" alt="screenshot" src="https://user-images.githubusercontent.com/1233318/33165374-ef51b10c-d079-11e7-86db-20a5a1b302b0.png">
<img width="146" alt="screenshot 1" src="https://user-images.githubusercontent.com/1233318/33165378-f1afbe12-d079-11e7-9a44-aa1d7185076f.png">
<img width="127" alt="screenshot 2" src="https://user-images.githubusercontent.com/1233318/33165379-f3939b04-d079-11e7-8073-a1127bad1655.png">
<img width="124" alt="screenshot 3" src="https://user-images.githubusercontent.com/1233318/33165380-f5634c04-d079-11e7-9fc8-e551e60c7b0f.png">


---

```xml
<net.alexandroid.utils.indicators.IndicatorsView
  android:id="@+id/indicator"
  android:layout_width="wrap_content"
  android:layout_height="wrap_content"
  android:gravity="center_vertical"
  android:orientation="horizontal"
  android:padding="5dp" // ===========================add this line
  app:indicatorSelectedSize="12dp"
  app:indicatorSize="8dp"
  app:layout_constraintBottom_toBottomOf="@+id/btn_next"
  app:layout_constraintEnd_toEndOf="parent"
  app:layout_constraintStart_toStartOf="parent"
  app:layout_constraintTop_toTopOf="@+id/btn_next"
  app:paddingBetweenIndicators="6dp"
  app:selectedDrawable="@drawable/bg_indicator_selected"
  app:unSelectedDrawable="@drawable/bg_normal"/>
```
<img width="135" alt="screenshot 4" src="https://user-images.githubusercontent.com/1233318/33165402-0acb4966-d07a-11e7-8e08-b6078473ac5b.png">
<img width="132" alt="screenshot 5" src="https://user-images.githubusercontent.com/1233318/33165405-0c76e2f2-d07a-11e7-9c4f-abc812f024f5.png">
<img width="115" alt="screenshot 6" src="https://user-images.githubusercontent.com/1233318/33165408-0e0f4276-d07a-11e7-8857-7fec0357d1c6.png">
<img width="107" alt="screenshot 7" src="https://user-images.githubusercontent.com/1233318/33165409-0f6c0a0a-d07a-11e7-9ce7-ee60d6383e37.png">

**Comment by Pulimet** [comment]
Fixed:  compile 'net.alexandroid.utils:indicators:1.6'

**Comment by NunciosChums** [comment]
Perfect!!
Thank you very much!
