### ISSUE TITLE
Consider migrating from jcenter

### ISSUE THREAD

**Issue by TheFaithOne** [Pulimet/Indicators-Library#3]
Jfrog is going to deprecate and disable jcenter services - artifact migration will be needed

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by Pulimet** [comment]
Thanks. I'll check it.

**Comment by OndraBasler** [comment]
Hi @Pulimet, did you make any progress with migrating it to MavenCentral? I know it is not crucial.
